services:
  elasticsearch:
    image: elasticsearch:8.17.6
    volumes:
      - $HOME/es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false